version: "3.8"

services:
  gateway:
    build: ./gateway-service
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - user-service
      - task-service

  task-service:
    build: ./task-service
    ports:
      - "5002:5002"
    env_file: .env

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    env_file: .env